# This is a TOML document

[default]
CONFIG_GEM5_KASLR_PROTECTION_HIGH = "n"
CONFIG_GEM5_KASLR_MAX_BIT = 39
CONFIG_GEM5_KASLR_ALIGN_BIT = 31

CONFIG_GEM5_KASLR_MODULE_PROTECTION_HIGH = "n"
CONFIG_GEM5_KASLR_MODULE_FINE_GRAINED = "n"
CONFIG_GEM5_KASLR_MODULE_MAX_BIT = 39
CONFIG_GEM5_KASLR_MODULE_ALIGN_BIT = 31

CONFIG_GEM5_ASLR_PROTECTION_HIGH = "n"
CONFIG_GEM5_ASLR_FINE_GRAINED="n"
CONFIG_GEM5_ASLR_MAX_BIT = 53
CONFIG_GEM5_ASLR_ALIGN_BIT = 48

CONFIG_GEM5_KASLR_PROTECTION_HIGH_KVM = "n"

[gem5]
CONFIG_GEM5_KASLR_PROTECTION_HIGH = "n"

[gem5_protect]
CONFIG_GEM5_KASLR_PROTECTION_HIGH = "y"

[gem5_protect_module]
CONFIG_GEM5_KASLR_MODULE_PROTECTION_HIGH = "y"

[gem5_protect_both]
CONFIG_GEM5_KASLR_PROTECTION_HIGH = "y"
CONFIG_GEM5_KASLR_MODULE_PROTECTION_HIGH = "y"

[gem5_protect_user]
CONFIG_GEM5_ASLR_PROTECTION_HIGH = "y"

[gem5_protect_text_user]
CONFIG_GEM5_KASLR_PROTECTION_HIGH = "y"
CONFIG_GEM5_ASLR_PROTECTION_HIGH = "y"

[gem5_protect_module_user]
CONFIG_GEM5_KASLR_MODULE_PROTECTION_HIGH = "y"
CONFIG_GEM5_ASLR_PROTECTION_HIGH = "y"

[gem5_protect_all]
CONFIG_GEM5_KASLR_PROTECTION_HIGH = "y"
CONFIG_GEM5_KASLR_MODULE_PROTECTION_HIGH = "y"
CONFIG_GEM5_ASLR_PROTECTION_HIGH = "y"

[gem5_protect_kvm]
CONFIG_GEM5_KASLR_PROTECTION_HIGH = "y"
CONFIG_GEM5_KASLR_PROTECTION_HIGH_KVM = "y"

[gem5_protect_both_kvm]
CONFIG_GEM5_KASLR_PROTECTION_HIGH = "y"
CONFIG_GEM5_KASLR_MODULE_PROTECTION_HIGH = "y"
CONFIG_GEM5_KASLR_PROTECTION_HIGH_KVM = "y"

[gem5_protect_all_kvm]
CONFIG_GEM5_KASLR_PROTECTION_HIGH = "y"
CONFIG_GEM5_KASLR_MODULE_PROTECTION_HIGH = "y"
CONFIG_GEM5_ASLR_PROTECTION_HIGH = "y"
CONFIG_GEM5_KASLR_PROTECTION_HIGH_KVM = "y"
